name: tag-preview
run-name: Tag Preview
on:
  # release a preview weekly
  schedule:
    - cron: 0 5 * * 1
  # or manually as needed
  workflow_dispatch: {}
jobs:
  tag-release:
    name: Tag Preview
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Tag Preview Release
        env:
          GH_TOKEN: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |-
          TAG=$(date "+v%Y-%m-%d-preview")
          PREVIOUS=$(gh release ls --exclude-pre-releases --exclude-drafts --order=desc --limit=1 --json=tagName --jq=".[0].tagName")
          gh release create $TAG --target ${{ github.sha }} --prerelease --latest=false --generate-notes --notes-start-tag=$PREVIOUS
