
name: Update GPG Keys

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  workflow_dispatch: {}  # Allow manual trigger

jobs:
  update-corretto-key:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Download latest Corretto key
        run: curl -sL https://apt.corretto.aws/corretto.key | sed 's/[[:space:]]*$//' > superchain/gpg/corretto.asc

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          commit-message: 'chore: update Corretto GPG key'
          title: 'chore: update Corretto GPG key'
          body: 'Automated update of Corretto GPG key from https://apt.corretto.aws/corretto.key'
          branch: update-corretto-key
          delete-branch: true
          labels: auto-approve